In [1]:
import numpy as np

arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

print("Array is of type: ", type(arr))

print("No. of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [2]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [3]:
b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [4]:
d = np.full((3, 3), 6, dtype = 'complex')
print("\nAn array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [5]:
# creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# create an array with random values
e = np.random.random((2,2))
print("\nA random array:\n", e)


A random array:
 [[0.14833383 0.45544417]
 [0.37098451 0.34734067]]


In [7]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [8]:
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [9]:
cond = arr > 0
temp = arr[cond]
print("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [10]:
a = np.array([1, 2, 5, 3])

print("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [11]:
print("Multiplying each element by 10:", a*10)

Multiplying each element by 10: [10 20 50 30]


In [12]:
arr = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])

In [13]:
print("Largest element is:", arr.max())
print("Row-wise maximum elements:", arr.max(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [14]:
print("Column-wise minimum elements:", arr.min(axis = 0))

Column-wise minimum elements: [1 1 2]


In [15]:
print("Sum of all array elements:", arr.sum())

Sum of all array elements: 38


In [16]:
print("Cumulative sum along each row:\n", arr.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [17]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [18]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [19]:
a = np.random.randn(2,3)
print(a)


[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


In [20]:
a = np.random.randint(5,10,3)
print(a)

[7 9 6]


In [21]:
element = np.random.choice([1,4,3,2,11,27])
print(element)

4
